# kAFL configuration
#
# All configuration options can be set by config file or argument.
# Names of config option mostly match the supported long form argument.
#
# Options are set (and overridden) in following order:
# 1. Hardcoded defaults in config.py argparser setup
# 2. Python package default (config_default.py)
# 3. Global and user-specific configs in common search paths,
#    e.g. $XDG_CONFIG_DIR or ~/.config/kafl/config.yaml
# 4. File provided via KAFL_CONFIG_FILE environment
# 5. File kafl.yaml in current working directory
# 6. Command line arguments, including argparse @file option
#
# By default, options 1+2 are used for base configuration,
# while target and campaign-specifc customization is done
# via option 4 and 6.
#

# default tool paths
qemu_path: $QEMU_ROOT/x86_64-softmmu/qemu-system-x86_64
ptdump_path: $LIBXDC_ROOT/build/ptdump_static
radamsa_path: $RADAMSA_ROOT/bin/radamsa

# default qemu configuration
qemu_base: -enable-kvm -machine kAFL64-v1 -cpu kAFL64-Hypervisor-v1,+vmx -no-reboot -net none -display none
qemu_append: nokaslr oops=panic nopti mitigations=off console=ttyS0
qemu_serial: -device isa-serial,chardev=kafl_serial
